export const dadosMestres = {
  branca: [
    {
      id: "sarara",
      nome: "Juvenal da Silva Pereira",
      apelido: "Mestre Sarará",
      inicio: "1977",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/conselho-mestres/Membros/sarara.png",
      nucleo: "Mato Grosso",
      historia:
        "A jornada de Mestre Sarará na capoeira teve início em agosto de 1977, no SESC do Setor Universitário, em Goiânia. Sob a orientação de Mestre Passarinho, ele treinava ao lado de nomes que viriam a se tornar grandes referências, como Mestre Suíno e Mestre Ilustre. Sarará, que inicialmente alcançou a graduação de lenço amarelo, testemunhou e participou da evolução do sistema de graduações, que adotou as cores da bandeira do Brasil. Em 1990, Mestre Suíno formou seus primeiros mestres, incluindo Sarará, que a partir de então adotou o apelido que o acompanha até hoje. Em 1999, ele estabeleceu um importante trabalho em Cáceres-MT, colaborando com programas sociais e instituições de ensino. Em uma experiência enriquecedora, Mestre Sarará viveu na Europa por dois anos a partir de 2004, deixando um legado de trabalho e conhecimento em cidades espanholas como Bilbao, Vitória e Valência. De volta ao Brasil em 2006, consolidou projetos na Argentina (Córdoba), Trindade e Goiânia, incluindo parcerias com a Polícia Militar e o Projeto Arte e Educação. Nos anos seguintes, Mestre Sarará dedicou-se a ministrar cursos de capacitação e a organizar eventos para seus alunos em diversas cidades de Goiás, São Paulo e Mato Grosso, consolidando sua influência na capoeira nacional. Em 2018, esteve em Rondonópolis, retornando a Cáceres em 2019, mantendo sua paixão e trabalho ativos.",
    },
    {
      id: "piau",
      nome: "JOSÉ CARLOS DE OLIVEIRA",
      apelido: "MESTRE PIAU",
      instagram: "@mestrepiau",
      inicio: "1982",
      pais: "Irlanda",
      bandeira: "irlanda",
      img: "../../assets/images/conselho-mestres/Membros/piau.png",
      nucleo: "IE",
      historia:
        "Comecei Capoeira em 1982, no meio do ano, no SESC do Setor Universitário. Treinava na turma de terças e quintas, e de vez em quando, na turma de sábado e domingo. A gente trabalhava na empresa e ganhava o direito de frequentar o clube dos comerciários. Quando estava no clube, eu sempre escutava o barulho, instrumentos tocando e, curioso, um dia subi as escadas em direção ao salão de festa para ver de que se tratava.Logo quando entrei no salão, Mestre Suíno falou: “entra e fecha porta”. Entendi que o barulho poderia incomodar outros ambientes. E eu vi o Fiapo, um excelente capoeirista, um dos melhores da época, executando giro de mão, mortal, e fiquei super encantado. Ele era um conhecido meu, seu trabalho era vizinho ao meu, no escritório de contabilidade, na rua 09 com a rua 04, onde eu trabalhei por 12 anos.O Mestre Suíno disse que se eu quisesse fazer inscrição era só descer. Então fiz a inscrição e nunca mais parei. Meus colegas contemporâneos, mais novos ou mais antigos que eu, eram Saúva, Marujo, Tourão, e os veteranos daquela época eram o Mestre Sarará, que se chamava Esqueci, o Fiapo, Deise, Girico e Chaminé. A Lagartixa era fogo, pois era muito difícil um homem jogar mais que ela: enfrentava os homens, partia para cima mesmo, e quem não tomava cuidado apanhava. O Grupo tinha muitos outros bons capoeiristas mas não me lembro dos nomes.",
    },
    {
      id: "xoroquinho",
      nome: "ELIAS FERNANDO RIBEIRO",
      apelido: "MESTRE XOROQUINHO",
      instagram: "@eliasfernandoribeiro",
      inicio: "1966",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Rondônia",
      historia:
        "Sou conhecido como MESTRE XOROQUINHO, comecei a capoeira em 1966, aos 10 anos de idade, na cidade de Poços de Caldas-MG, com o saudoso Mestre José Capoeira. Fui formado mestre em 1985, no Grupo Lagoa do Abaeté do Mestre Itabuna (São Paulo/SP) e, desenvolvendo a Capoeira no Estado de Rondônia, na cidade de Porto Velho, a partir do referido ano, pela Associação Esportiva Barra Vento - AEBV. Por meio do Graduado MADEIRA (Edson Fernando Ribeiro), meu filho, tive contato com o Contramestre Pequinês em 1997 e, embora tenham envidado esforços visando concretizar a presença do CM Pequinês em evento promovido pela AEBV, não obtivemos êxito em razão da sua agenda sobrecarregada.Contudo, o CM Pequinês nos indicou outro excelente capoeirista para representar o Grupo Candeias no evento tradicional que promovemos em Porto Velho (GRAN-DE RODA DE CAPOEIRA DO ESTADO DE RONDÔNIA), qual seja, Contra Mestre Secão (GO), que se fez presente no evento ocorrido em 1998. Pelo contato com o CM Secão, passamos a fortalecer os laços de amizade, camaradagem e cooperação com o Grupo Candeias, o que me levou a participar no ano de 1999 de evento realizado pelo Grupo Candeias, na Cidade de Goiânia-GO, no qual o CM Secão me apresentou ao Mestre Suíno, responsável pela condução dos destinos do Grupo Candeias.Fui convidado pelo Mestre Suíno a passar uma tarde em sua residência para assistir alguns documentários sobre a capoeira e conversar a respeito desta nobre arte, tarde esta que foi muito proveitosa, oportunidade em que tive meus conhecimentos postos à prova pelas indagações por parte do Mestre Suíno, o qual é um profundo conhecedor da capoeira.",
    },
    {
      id: "cabeca",
      nome: "CLÁUDIO DOS SANTOS SILVA",
      apelido: "MESTRE CABEÇA",
      instagram: "@mestre_cabeca",
      inicio: "1979",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Nasci na cidade de Goiânia, no ano de 1971, no dia 04 de agosto. Iniciei na capoeira com a influência do meu irmão, atualmente conhecido como Mestre Ilustre. Minha primeira experiência e minha primeira aula foi com ele, que na época era conhecido como Mestre Salário. Ele nos ensinava em um pequeno gramado que tinha perto da nossa casa, no Jardim Novo Mundo e, a partir daqueles momentos, começamos a pegar gosto. Por influência dele, fui levado para o SESC e a história continuou. Tinha oito ou nove anos de idade quando comecei a treinar no Grupo Infantil do SESC, em um momento em que o grupo estava passando por um processo de transição, do nome São Bento Pequeno para Anglo-Regional. Nesse grupo, meus amigos eram o Pelego, o Ziquinho, Luiz Carlos, e também tive a oportunidade de conhecer o Mestre Gueroba, Mestre Xeréu e o Contramestre Rato. O que eu achava legal era termos um tratamento especial. No SESC, tinham algumas estagiárias que sempre faziam reuniões conosco, além de várias atividades de recreação e viagens, por exemplo, para piqueniques, uma das que mais fizemos. Lembro também que o Mestre Besouro era um dos nossos guias, um dos responsáveis por nós, por ser mais velho e por conhecer vários locais de turismo na região de Aparecida. Eram ótimos passeios. E também podíamos aproveitar as dependências do SESC, que era um clube. Inclusive minha mãe, Dona Iraci, também trabalhava lá.",
    },
  ],
  brancaVermelha: [
    {
      id: "saci",
      nome: "ANTÔNIO BARBOSA DA SILVA",
      apelido: "MESTRE SACI",
      instagram: "",
      inicio: "1984",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Acre",
      historia:
        "Sou conhecido como Mestre Saci, nascido em 1974 em Rio Branco–AC. Iniciei na capoeira por volta de 1984, treinando informalmente no quintal de um amigo e, em 1985, comecei a treinar com o Professor Dendê. Recebi minha primeira corda no Grupo Capoeira Brasil com o Professor Olho de Peixe. Desde 1993, comecei a dar aulas e expandi meu trabalho por vários bairros de Rio Branco, além dos municípios de Senador Guiomard e Bujari. Em 1999, fui graduado professor (corda roxa) no Capoeira Brasil. Após divergências internas, deixei o grupo em 2000 e conheci o Grupo Candeias em 2001 durante evento em Porto Velho. Após um estágio de dois anos no Sistema Candeias de Ensino, fui oficialmente integrado ao grupo em 2003. Fui promovido a contramestre de 1º grau em 2006, contramestre de 2º grau em 2009 e Mestre do Grupo Candeias em 2015. Formado em Educação Física, viajei por vários estados e países levando a capoeira e formando gerações de alunos no Acre, onde sigo atuando até hoje.",
    },
    {
      id: "xereu",
      nome: "SANDRO PAULO DE ALMEIDA",
      apelido: "MESTRE XERÉU",
      instagram: "@mestrexereugyn",
      inicio: "1983",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Sou de 03 de fevereiro de 1972, natural de Goiânia-GO. Iniciei a minha vida na capoeira, com Mestre Suíno no ano de 1983, com 11 anos de idade no clube SESC, localizado no Setor Universitário. Na ocasião, fiz parte do Grupo Infantil e participávamos de várias apresentações. Numa delas, marcou o uso de um figurino específico, as batas de renda azul e branca. No início, fui muito influenciado pelos meus primos que eram capoeiristas, eram o Chaminé, Eclipse e o Chaminé 2. Por volta dos meus 18 anos, fiquei dois anos sem treinar. Meu retorno foi com 20 anos e na ocasião percebi que muita coisa havia mudado até mesmo o local de treino. Então fui para o DCE (Diretório Central de Estudantes da Pontifícia Católica de Goiás), e lá me enturmei novamente com os antigos e com os novatos. Danilo, que dirigia um Grupo de Teatro, me convidou para fazer parte de uma peça e foi uma experiência muito bacana. Mais a frente, comecei a ajudar o Mestre Suíno com aulas nas terças e quintas e algumas aulas no Mestre Glauber. Logo que o Mestre Glauber foi para os EUA, em 1996, deixou seu trabalho comigo. A partir disso, meu trabalho só cresceu e comecei a me destacar como professor.",
    },
    {
      id: "tiziu",
      nome: "MARCOS ANTÔNIO DE LIMA RIBEIRO",
      apelido: "MESTRE TIZIU",
      instagram: "@tiziu_marcos",
      inicio: "1985",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Sou conhecido pelo mundo capoeirístico como Mestre Tiziu, formado em 2011 pelo presidente do GRUPO CANDEIAS, ELTO PEREIRA DE BRITO conhecido mundialmente por Mestre Suíno. Segundo semestre de 1985, foi meu inicio na capoeira, no colégio ESTADUAL PROF. JOSÉ ALVES DE ASSIS no Setor dos Afonsos, eu era uma pessoa fascinada por lutas e estava ainda organizando minha mudança, pois tinha acabado de chegar a Goiânia. Meus pais resolveram vir para Goiânia nem sei por que, pois meu pai viajava muito e minha mãe, na maioria das vezes, tinha que se virar para cuidar das crianças, sozinha. Deve ser por isso que não ficávamos muito tempo em lugar nenhum, mas, graças a Deus Goiânia foi o melhor lugar para ficar. Passaram as férias e as aulas voltaram, teve uma visita em sala de aula, na qual o Professor Besouro (Rogério Pereira da Silva), responsável pela turma de capoeira que eu nem sabia o que era, nem como era e nem para que servia, explicou que tinha aulas aos finais de semanas e que haveria alguns dias da semana também, então resolvi dá uma olhadinha para saber realmente do que se tratava essa tal capoeira. Na hora do recreio, tinha um montão de gente para assistir e para fazer uma apresentação, com palmas, músicas e instrumentos, eles iam fazendo umas acrobacias e eles iam ganhando os alunos do colégio. E, eu lá de longe, ficava só olhando, pois era muito tímido e ficar na frente nunca, prefiro sempre ficar atrás e observar. Bom, então, eu pensei vou no final de semana para ver melhor a aula.",
    },
    {
      id: "gueroba",
      nome: "GILMAR PEREIRA DE CASTRO",
      apelido: "MESTRE GUEROBA",
      instagram: "@mestregueroba",
      inicio: "1985",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Gueroba",
      historia:
        "Conheci a Capoeira na Praça Cívica, local que frequentava com alguns amigos, e onde funcionava a Feira Hippie. Eu tinha entre 12 e 13 anos, e naquele local acontecia aos domingos, rodas de Capoeira. Após as rodas, ficava alguns Capoeiristas, inclusive eu. Nós ficávamos brincando, pulando e tentando fazer os movimentos que tínhamos visto. Em um passeio ao Clube SESC do Setor Universitário, no ano de 1985, estava acontecendo uma roda de capoeira e algo despertou em mim. Então me aproximei, pois há muito tempo queria treinar. Uma senhora chamada Maria das Graças percebeu meu interesse e me convidou a fazer capoeira, ela era a estagiária responsável pelo treino das crianças e adolescentes, de pronto aceitei o convite e comecei no domingo seguinte a treinar no Grupo Anglo-Regional. Logo no meu primeiro, tive o prazer de conhecer o meu Mestre, Mestre Suíno. Meus treinos era aos finais de semana, eu era um garoto miúdo, magro e de baixa estatura, então, mesmo tendo 14 anos me colocaram no grupo infantil. Cada vez mais me apaixonava pela Capoeira e no meu coração já havia a certeza que dali pra frente a Capoeira seria minha ideologia. Nós contávamos com o carinho e o incentivo da equipe do Clube SESC, que ao término das aulas de Capoeira, sempre faziam uma confraternização, seja na lanchonete próxima, ou nas comemorações dos aniversariantes. Eles também promoviam passeios para o Mutirama (Parque de diversão em Goiânia) ou para o Zoológico da cidade. Eu gostava demais de tudo isso, era muito bom! Quando as aulas acabavam tomávamos banho de piscina. Além das aulas do SESC, treinávamos nos parques e nas praças.",
    },
    {
      id: "iuna",
      nome: "VALDISE ÂNGELA DE ABREU",
      apelido: "MESTRA IÚNA",
      instagram: "@mestraiuna",
      inicio: "1985",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Dei início na Capoeira dia 23 de junho de 1985, no Grupo Surussal com o Contramestre Salário (atualmente, Ilustre, um dos Mestres formados por Mestre Suíno), na associação dos moradores do Jardim Novo Mundo. Mas, na verdade, comecei por acaso apenas por ter problemas respiratórios como bronquite alérgica e asmática. Meus irmãos já praticavam capoeira, Vantuir Alberto de Abreu ou Xavante (em memória) e Vanilson Alessandro de Abreu, Mestre Sazuki que mora na República Tcheca. Em uma das minhas últimas crises fiquei internada, o médico disse à minha mãe que seria bom se eu praticasse algum esporte, de preferência a natação, mas naquela época natação era algo mais elitizado e caro. Então, minha mãe me colocou, mesmo contra a vontade de meu pai, na Capoeira. Meu avô dizia que eu me tornaria uma vagabunda e meus irmãos, maloqueiros. Mal sabia ele que a sabedoria que minha mãe sempre teve nos tornou o contrário do que ele pensava. Em 1986, meu irmão Xavante foi convocado para participar dos JEBs, e ele foi o único a ganhar a medalha para o estado de Goiás, ficando em 3° lugar individual (ele era fenomenal).",
    },
    {
      id: "babuino",
      nome: "MARCONE DOS SANTOS COSTA",
      apelido: "MESTRE BABUÍNO",
      instagram: "@babuinomestre",
      inicio: "1982",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "",
      historia:
        "Nasci em João Pessoa-PB, sou casado, tenho quatro filhos e moramos em Recife-PE. Comecei na capoeira em 1982, nas férias de dezembro. Meu primeiro contato foi na escola. Eu saía da aula e sempre tinham uns amigos meus gingando, fazendo uns movimentos, e então eu comecei a imitá-los. Na época, eu também surfava, e tinha um cara que ficava fazendo uns movimentos de capoeira na beira da praia. Eu ficava olhando lá de dentro do mar, entre uma onda e outra, e quando saía do mar, ficava ali meio curioso vendo ele fazer uns golpes. Eu tinha um amigo que praticava, e ele às vezes saía para gingar com esse camarada lá fora, até que um dia fui convidado a fazer uns golpes. Como já havia aprendido com alguns na saída da escola, resolvi tentar. Depois disso, já não ia mais para a praia com muita intenção de surfar, mas sim de jogar capoeira. E fui convidado a treinar embaixo do prédio onde o Cara de Peixe morava, todos os dias à tarde. Depois do treino, descíamos para a praia para treinar mortais e aú sem o apoio das mãos.",
    },
  ],
  vermelha: [
    {
      id: "vivian",
      nome: "Vivian Alexandra de Abreu",
      apelido: "Mestra Vivian",
      instagram: "",
      inicio: "2021",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
    {
      id: "fyapo",
      nome: "ROOSEVELT ATAIDES DOS SANTOS",
      apelido: "MESTRE FYAPO",
      instagram: "@rooseveltasantos",
      inicio: "1978",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Comecei em 1978, por ser comerciário, no SESC do Setor Universitário, levado pelos amigos Celso (Cuecão) e Celmo. Na época, o responsável pelo grupo era o Mestre Passarinho, e o grupo chamava-se Grupo de Capoeira São Bento Pequeno do SESC. O Mestre Passarinho estava no Serviço Militar e o aluno mais velho e responsável pelo grupo era o Mestre Suíno, que na época tinha a graduação de lenço vermelho. Os alunos daquela época eram: Gafanhoto, Ganso, Minhocão, Descrente, Dragão, Macha Lenta, Macarrão, Strogonof, Curraleiro, Zorro, Doença, Cabaça, Kiko, Índio, Louva-Deus, Linguicinha, Salário Mínimo, Esqueci, Cabeça, Chorão, Piolho, Traíra, Lobó, Maguila, Dimorié, Xita, Tiziu, Chinelo, Girafa (Goiano), Coqueiro (Charm) e Foquinha. E as mulheres eram Salsicha, Requenguela, Lagartixa e Nega Tarú. Em janeiro de 1979, o Mestre Passarinho retornou à liderança do grupo após cumprir o tempo de serviço militar. Os treinos aconteciam no clube do SESC, na sala do primeiro andar, onde era o salão de festas. Afastávamos as mesas e cadeiras, limpávamos o salão e treinávamos aos sábados à tarde e domingos pela manhã. Em janeiro de 1979, peguei o primeiro lenço azul da sequência de Mestre Bimba e ganhei o primeiro campeonato interno.",
    },
    {
      id: "besouro1",
      nome: "ROGÉRIO PEREIRA DA SILVA",
      apelido: "MESTRE BESOURO",
      instagram: "@advogadorogerio",
      inicio: "1979",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "",
      historia:
        "Meu primeiro contato foi antes mesmo do grupo voltar a utilizar o nome Anglo-Regional. Na época, agosto de 1979 ou 1980, se chamava São Bento Pequeno. Eu tinha 8 ou 9 anos de idade, e meus pais haviam acabado de se separar. Foi quando comecei a andar com companhias erradas, que me convidavam para pular o muro do SESC, porque lá tinha piscina. Nós andávamos 37 km, pulávamos o muro e passávamos o dia no clube (se saísse pela portaria, não podia voltar). Acabava que não nos alimentávamos, só quando sobrava um salgado ou pastel. Chegou até a virar rotina. Sempre ouvíamos um barulho no prédio, e um dia fui ver o que era. Fui recebido pelo Sarará, que me pediu para fazer inscrição, e assim o fiz com a assistente social. Nesse dia, nem quis voltar com meus amigos, pois fiquei encantado com a aula de capoeira. No outro dia voltei, ele me apresentou o “chefe”, e comecei a treinar. Lembro que eles faziam “corredor polonês”, polichinelos, corriam em volta da sala, faziam exercícios do exército, muitos abdominais e muitas flexões. Nesse início, conheci muita gente legal, como Girico, Marujo, Lobó, Salário, Fiapo, que eram mais velhos que a gente. Um ou dois anos depois, entrou o Cláudio (Mestre Cabeça), depois o Sandro (Mestre Xeréu), Gueroba, Rato. Existiam grupos separados e orientados por assistentes sociais. O grupo das crianças tinha um grande privilégio: agora eu podia entrar no clube sem precisar pular o muro e ainda ganhava lanche após os treinos. Tinha sempre um suco de caju e uma reunião para falar sobre diversos assuntos, como, por exemplo, sobre drogas.",
    },
    {
      id: "sauva",
      nome: "ALEX BARBOSA DA SILVA",
      apelido: "MESTRE SAÚVA",
      instagram: "",
      inicio: "1982",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Sou conhecido como MESTRE SAÚVA. Nasci em 28 de janeiro de 1964 e iniciei na capoeira no dia 22 de julho de 1982, após assistir a uma apresentação no SESC. No dia seguinte já estava matriculado e logo intensifiquei os treinos, participando de aulas em vários locais, como a ESEFEGO e o COLU, inclusive com o Mestre Suíno. Comecei a dar aula cedo, quando ainda estava entre a terceira e quarta corda, e enfrentei muita resistência ao ensinar capoeira em Jussara, onde fui pioneiro e formei alunos como o Miúdo. Após o nascimento do meu filho, retornei a Goiânia e segui dando aulas no Bairro Feliz, formando diversos alunos de destaque como Catatau, Santiago, Cigana e outros. Tive mais de 300 alunos ativos, mas com mudanças de espaço, perdi parte da turma e me adaptei ensinando em igrejas e academias. Sofri um acidente grave que afetou meu sistema nervoso, mas sigo usando a própria capoeira como forma de reabilitação. Sigo firme no propósito de ensinar e manter viva a tradição que transformou minha vida.",
    },
    {
      id: "santiago",
      nome: "SANTIAGO PEREIRA GOMES",
      apelido: "MESTRE SANTIAGO",
      instagram: "",
      inicio: "1988",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiás",
      historia:
        "Sou conhecido como MESTRE SANTIAGO. Meu primeiro contato com a capoeira foi ainda criança, assistindo às aulas do Mestre Osvaldo, aluno de Mestre Bimba, pelas frestas de um barracão, sem poder participar por falta de recursos. Comecei a treinar de fato em 1988, com o Professor Saúva, no Centro Comunitário do Bairro Feliz. Para pagar as aulas, capinei lotes e carreguei terra. Superei dificuldades e brincadeiras maldosas no início, mas fui persistente e continuei treinando quando muitos desistiram. Passei por diversos professores e espaços, como o Mestre Piau e a academia Equilíbrio. Fui ao quartel em Brasília em 1994, onde enfrentei desafios devido à violência no meio da capoeira local. De volta a Goiânia, iniciei um trabalho próprio no Bairro Feliz e, mesmo formado na corda verde escura, tive que passar por novas formações e orientações com o Mestre Suíno para poder dar aulas dentro do padrão do Grupo Candeias. Fiz parceria com o Mestre Sarará, onde avancei nas graduações até quase contramestre, e após sua saída, continuei com o Mestre Suíno no DCE. Tive muitos alunos ao longo dos anos e assumi turmas em diversos espaços, incluindo o tradicional Clube Jaó. A persistência, a disciplina e o apoio do Grupo Candeias foram fundamentais na minha caminhada.",
    },
    {
      id: "senzala",
      nome: "DERVAL CORREA DA SILVA",
      apelido: "MESTRE SENZALA",
      instagram: "",
      inicio: "1986",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiás",
      historia:
        "Sou conhecido como MESTRE SENZALA. Nasci em 1972, na cidade de Água Limpa, município de Faina-GO. Conheci a capoeira por volta de 1986, levado por um amigo para assistir às aulas do Professor Pajé, do Grupo São Bento Pequeno. Fiquei impressionado e comecei a treinar, permanecendo por três anos. Em 1989, me mudei para Goiânia e iniciei com o Professor Piau na Associação dos Moradores do Jardim Vila Boa. Já com algum conhecimento e o apelido Senzala, pedi para começar do início. Quando o Piau parou de dar aula, me levou ao DCE da Universidade Católica e me apresentou ao Mestre Suíno, com quem estou até hoje. O Grupo Candeias foi essencial para o meu crescimento, proporcionando eventos marcantes como o 'Goiás Mostra Suas Pernas' e o jogo do Mestre Canjiquinha com Mestre Charm. Com apoio do grupo, me formei em Educação Física e sigo como mestre, tendo orgulho de plantar minha árvore nesse solo. Agradeço ao Mestre Suíno, que sempre foi como um pai para mim, incentivando-nos a estudar para transformar nossa realidade.",
    },
    {
      id: "lula",
      nome: "LUIZ GUSTAVO DE MELO",
      apelido: "MESTRE LULA",
      instagram: "",
      inicio: "anos 1990",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Maceió - AL",
      historia:
        "Sou conhecido como MESTRE LULA. Nasci em 10 de janeiro de 1974, e coordeno atualmente um trabalho sólido de capoeira na cidade de Maceió, Alagoas. Conheci o Grupo Candeias após um amigo me falar sobre o grupo e seu mestre, o Mestre Suíno. Tive meu primeiro contato com ele em um evento em Brasília e, com o tempo, o convidei para conhecer meu trabalho em Maceió, na época como contramestre do Grupo Ginga Brasil. Após sua visita, fui oficialmente acolhido no Grupo Candeias, e comecei meu processo de adaptação. Fui diversas vezes a Goiânia para aprender com o grupo e com o Mestre Suíno, passando por experiências marcantes, como a aula de ginga de frente para a parede e uma roda intensa no Setor Universitário. Passei pelas graduações até ser formado mestre em 2014, durante o Fest Candeias Internacional em Maceió, por Mestre Suíno. Sofri um AVC, que me afastou temporariamente, mas retornei com força. Hoje, tenho alunos atuando em diversas cidades e países, como o Professor Thiaguinho na Espanha, e coordeno um grupo forte em Alagoas. Em 2018, realizei o Fest Internacional, celebrando 20 anos do Grupo Candeias em Maceió, com a frase marcante: 'Você quer bater palmas para outro jogar, ou quer fazer os outros pararem de bater palmas vendo você jogar? Então treine!'",
    },
    {
      id: "mola",
      nome: "KEINE BERNARDES MENDES",
      apelido: "MESTRE MOLA",
      instagram: "",
      inicio: "1989",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Irlanda",
      historia:
        "Sou conhecido como MESTRE MOLA, apelido que ganhei pela minha flexibilidade e gosto por movimentos de coluna. Comecei na capoeira em 1989, em Aparecida de Goiânia-GO, com o então Professor Besouro, junto com vários colegas que se tornariam referência. Em 1995, iniciei um novo ciclo treinando com o Mestre Suíno no DCE da UFG, enfrentando dificuldades, mas sem nunca desistir. Formei alunos de destaque e participei de eventos em Goiás e no Brasil, conhecendo grandes mestres como Suassuna, Onça Negra, Gato, Barrão, Acordeon, entre outros. Em 2003, recebi o convite do Mestre Piau para levar a capoeira para a Irlanda, onde vivo e trabalho até hoje. Tive muitas experiências marcantes, desde apresentações com dança do fogo até trotes com veteranos do grupo. Sinto saudade dessa época, pois as viagens e brincadeiras fortaleciam os laços dentro do Grupo Candeias.",
    },
    {
      id: "mikim",
      nome: "JOEL RIBEIRO DOS SANTOS",
      apelido: "MESTRE MIKIM",
      instagram: "",
      inicio: "1979",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Comecei a treinar capoeira aos 13 anos no SESC, influenciado pela curiosidade ao ouvir as rodas. Sou discípulo do Mestre Suíno e recebi o apelido Mikim durante a roda. Em 1979, já treinava com frequência e participei do Grupo Anglo-Regional, que depois virou Candeias. Sempre fui extrovertido e gostava das excursões e apresentações do grupo. Entre momentos marcantes, destaco a valorização ao receber a corda surpresa e a participação nas graduações. Passei por momentos difíceis, como a quebra do nariz que me afastou dos treinos por seis meses. Recordo também os treinos duros, como a sabatina e o corredor polonês, que faziam parte da formação. Planejo que futuras graduações sejam sempre comemoradas com homenagens aos alunos.",
    },
    {
      id: "amazonas",
      nome: "Sandra Regina Prudêncio",
      apelido: "Mestra Amazonas",
      instagram: "",
      inicio: "1985",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Nasci em Goiânia em 1969 e comecei a treinar capoeira em 1985 no Grupo São Bento Pequeno, criado pelo Mestre Passarinho. Em 1988, participei de uma seletiva para um campeonato brasileiro, onde conheci o Mestre Suíno, que me convidou para treinar no seu grupo. Em 1989 entrei para o Grupo Anglo Regional do SESC, antigo nome do Grupo Candeias. Fui pioneira como mulher em várias conquistas, como o primeiro salto mortal feminino em evento oficial (1995) e o primeiro batizado feminino do grupo. Participei de muitos campeonatos, apresentações e viagens, nacionais e internacionais. Atualmente, me preparo para ser Mestra no grupo, focando no ensino da capoeira com qualidade e respeito aos fundamentos da arte.",
    },
    {
      id: "besouro2",
      nome: "Agnaldo Batista",
      apelido: "Mestre Besouro",
      instagram: "",
      inicio: "1986",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Anápolis",
      historia:
        "Meu primeiro contato com a capoeira foi em 1986, aos 15 anos, em um desfile. Comecei a treinar em 1987 com o Mestre Tuísca, do grupo Flor da Gente, e depois com Mestre Espiga até 1988. Participei do Festival Anapolino de Capoeira, com presença de grupos importantes. Depois de um afastamento, voltei em 1992-93 quando Mestre Suíno ensinava capoeira para jogadores de futebol em Anápolis. Em 1993 entrei no Grupo Candeias, onde tive contato com grandes mestres e fiz várias viagens e excursões. Minhas maiores conquistas foram a reflexão pessoal e o aprimoramento do ensino da capoeira. Tenho grande gratidão pelo Mestre Suíno e pelo Grupo Candeias, onde atuo há quase 30 anos.",
    },
    {
      id: "casagrande",
      nome: "Aparecido Corrêa da Silva",
      apelido: "Mestre Casa Grande",
      instagram: "",
      inicio: "1986",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Comecei a capoeira em 1986 na Praça do Chafariz, na Cidade de Goiás, com capoeiristas locais. O ensino era por livros e ajuda de professores como Chuluca, Chando, Leninho e Ibéria. O grupo cresceu, com o policial Pajé assumindo os treinos e formando o Grupo São Bento Pequeno. Em 1995, mudei para Goiânia, onde conheci o mestre Suíno e entrei no Grupo Candeias. Participei de vários eventos e graduações, dei aulas no Jardim Nova Esperança e montei minha academia em 2010. Em 2019, receberei a corda de mestre pelo Grupo Candeias, entregue pelo mestre Suíno.",
    },
    {
      id: "dende",
      nome: "Marcia Regina das Neves Almeida",
      apelido: "Mestra Dendê",
      instagram: "",
      inicio: "2022",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
    {
      id: "jiboia",
      nome: "Deurivan Marques da Silva",
      apelido: "Mestre Jiboia",
      instagram: "",
      inicio: "2019",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
    {
      id: "biliu",
      nome: "Flávio da Conceição",
      apelido: "Mestre Biliu",
      instagram: "",
      inicio: "2021",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
    {
      id: "escravo",
      nome: "Franco Fernandes Pedrosa",
      apelido: "Mestre Escravo",
      instagram: "",
      inicio: "2021",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
    {
      id: "molejo",
      nome: "Marcos Elias Alves de Melo",
      apelido: "Mestre Molejo",
      instagram: "",
      inicio: "2021",
      pais: "França",
      bandeira: "franca",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Paris",
      historia:
        "Em breve.",
    },
    {
      id: "tucano",
      nome: "Hugo de Almeida Barbosa",
      apelido: "Mestre Tucano",
      instagram: "",
      inicio: "2022",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
    {
      id: "fenix",
      nome: "Thiago Gaspar da Cruz",
      apelido: "Mestre Fênix",
      instagram: "",
      inicio: "2022",
      pais: "Estados Unidos",
      bandeira: "eua",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Seattle",
      historia:
        "Em breve.",
    },
    {
      id: "cacador",
      nome: "Carlos Alberto Pires dos Santos",
      apelido: "Mestre Caçador",
      instagram: "",
      inicio: "2022",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
    {
      id: "guerreiro",
      nome: "Lindomar Fernandes Pedrosa",
      apelido: "Mestre Guerreiro",
      instagram: "",
      inicio: "2022",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
    {
      id: "leitao",
      nome: "Wilson dos Santos de Jesus",
      apelido: "Mestre Leitão",
      instagram: "",
      inicio: "2022",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
    {
      id: "negovento",
      nome: "José Carlos Barbosa Santos",
      apelido: "Mestre Nego Vento",
      instagram: "",
      inicio: "2022",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
    {
      id: "miudo",
      nome: "Odair José da Cruz",
      apelido: "Mestre Miúdo",
      instagram: "",
      inicio: "2022",
      pais: "Brasil",
      bandeira: "brasil",
      img: "../../assets/images/logo/logo2.png",
      nucleo: "Goiânia",
      historia:
        "Em breve.",
    },
  ],
};
